// WebChatSales Demo Platform - Real Functionality

class WebChatSalesDemo {
    constructor() {
        this.currentBusiness = {
            name: "Paws & Claws Pet Emporium",
            type: "Pet Services",
            description: "Professional pet grooming and care services"
        };
    }

    // Social Media Generator
    generateSocialMediaPost(platform, message) {
        const templates = {
            facebook: {
                text: `🐕 ${this.currentBusiness.name} - ${message}\n\n#PetCare #${this.currentBusiness.name.replace(/\s+/g, '')}`,
                hashtags: ['PetCare', 'DogGrooming']
            },
            tiktok: {
                text: `Watch our happy pets! 🐾 ${message}\n\n#PetTok #${this.currentBusiness.name}`,
                hashtags: ['PetTok', 'PetTransformation']
            },
            twitter: {
                text: `Why pet owners choose ${this.currentBusiness.name}: ${message}\n\n#PetServices #QualityCare`,
                hashtags: ['PetServices', 'ProfessionalGrooming']
            }
        };

        return templates[platform] || templates.facebook;
    }

    // Website Generator
    generateWebsiteHTML(businessName, services) {
        return `
<!DOCTYPE html>
<html>
<head>
    <title>${businessName} - Professional Pet Services</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 0; padding: 0; background: #36454F; color: white; }
        .header { background: #000080; padding: 2rem; text-align: center; }
        .services { padding: 2rem; display: grid; gap: 1rem; }
    </style>
</head>
<body>
    <div class="header">
        <h1>${businessName}</h1>
        <p>Generated by WebChatSales AI</p>
    </div>
    <div class="services">
        <h3>Our Services:</h3>
        <p>${services}</p>
    </div>
</body>
</html>`;
    }
}

// Initialize demo platform
const demo = new WebChatSalesDemo();
